# Generated by Django 5.1.2 on 2024-10-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='flan',
            name='img_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='flan',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flan',
            name='slug',
            field=models.SlugField(default='default-slug'),
        ),
    ]
