# Generated by Django 5.1.2 on 2024-11-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descripcion', models.TextField(default='')),
                ('img', models.URLField(default='')),
                ('in_earth', models.BooleanField(default=True)),
            ],
        ),
    ]
